# Generated by Django 4.1.2 on 2022-12-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diaryitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_id', models.CharField(max_length=10)),
                ('diary_body', models.CharField(max_length=1000000)),
                ('created_time', models.CharField(max_length=20)),
                ('updated_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Diarylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('diary_title', models.CharField(max_length=100)),
                ('diary_id', models.CharField(max_length=10)),
                ('created_time', models.CharField(max_length=20)),
                ('updated_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('created_time', models.CharField(max_length=20)),
            ],
        ),
    ]
