# Generated by Django 4.1.2 on 2022-12-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryitems',
            name='id',
        ),
        migrations.RemoveField(
            model_name='diarylist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='diaryitems',
            name='dairy_item_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='diaryitems',
            name='diary_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diarylist',
            name='diary_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diarylist',
            name='diary_title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='diarylist',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
