# Generated by Django 4.1.2 on 2022-12-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_api', '0002_remove_diaryitems_id_remove_diarylist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(db_index=True, default=None, max_length=10),
        ),
    ]
