# Generated by Django 4.1.2 on 2022-12-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_api', '0003_alter_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryitems',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
