# Generated by Django 4.1.2 on 2022-12-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_api', '0004_diaryitems_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryitems',
            name='dairy_item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
